title: SKY-Pulse
description: "Your application description"
owner_name: Your Name
github_username: your-username
github_repo: "SKY-Pulse"
baseurl: ""
future: true
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
header_pages:
  - navigation/search.md
  - navigation/about.md
