title: SKY-Pulse
description: "Track your volunteer hours and participation in SKY-Pulse events"
owner_name: Rudra Joshi
github_username: RudraBJoshi 
github_repo: "SKY-Pulse"

# If you DON'T have a custom domain, use the repo name below:
baseurl: "/SKY-Pulse" 
future: true
remote_theme: pages-themes/cayman

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag

header_pages:
  - navigation/search.md
  - navigation/about.md
  - hacks/hours-tracker.md